version: 2
 jobs:
   build:
     machine:
       enabled: true
     steps:
       - add_ssh_keys:
           fingerprints:
             - "SHA256:yNjfYNINYsuPF6tzj/n4jL+/P4omgHwRKdHgX0V63JY dkawanam@daisuke-ga"
       - run:
           name: Deploy Over SSH
           command: |
             ssh dkawanam@130.211.127.76  "cd /var/www/html; git pull origin master:master;
 # workflows:
 #   version: 2
 #   build-and-deploy:
 #     jobs:
 #       - deploy:
 #           filters:
 #             branches:
 #               only: master
