version: 2
jobs:
  build:
     machine:
       enabled: true
     steps:
       - add_ssh_keys:
           fingerprints:
             - "31:da:0e:03:83:88:f1:a0:f7:b3:30:9a:2f:9f:35:b7"
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh dkawanam@130.211.127.76 "cd /var/www/html; sudo git pull origin master:master;"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
