version: 2
jobs:
  build:
     machine:
       enabled: true
     steps:
       - add_ssh_keys:
           fingerprints:
             - "5d:c3:61:d7:76:8b:68:f7:3e:cf:5a:c4:b2:f0:3a:f5"
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            sudo ssh dkawanam@130.211.127.76 "cd /var/www/html; sudo git pull origin master;"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
